[versions]
android-gradle-plugin = "9.0.0"
gradle-plugin-publish = "2.0.0"
gradle-test-retry = "1.6.4"
gradle-versions = "0.53.0"
guava = "33.5.0-jre"
junit-jupiter-api = "6.0.1"
kotest = "6.0.7"
kotlin = "2.3.0"
kotlinx-serialization-json = "1.9.0"
ktfmt = "0.25.0"
version-catalog-update = "1.0.1"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter-api" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = "io.kotest:kotest-framework-datatest:5.9.1"
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
gradle-test-retry = { id = "org.gradle.test-retry", version.ref = "gradle-test-retry" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
